default_agent: wheelseyedemo_Agent
agents:
  wheelseyedemo_Agent:
    name: wheelseyedemo_Agent
    language: python
    node_version: null
    entrypoint: /Users/casentars/Documents/wheelseye/agentcore/wheelseyedemo/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/casentars/Documents/wheelseye/agentcore/wheelseyedemo/src
    aws:
      execution_role: arn:aws:iam::361428600572:role/bedrock-agent-core-role
      execution_role_auto_create: false
      account: '361428600572'
      region: ap-south-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-361428600572-ap-south-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: wheelseyedemo_Agent-3pBn64CUg5
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:361428600572:runtime/wheelseyedemo_Agent-3pBn64CUg5
      agent_session_id: 5bf00669-9e46-495d-a655-c764d9ca9259
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
